version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'go'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
  web:
    build: .
    env_file:
      - .env
    command: go run .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
